"""initial schema: statements and transactions

Revision ID: 2c57823a4419
Revises:
Create Date: 2026-04-12 14:06:38.763584

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c57823a4419'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_holder', sa.String(), nullable=False),
    sa.Column('card_number_masked', sa.String(), nullable=False),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('cut_off_date', sa.String(), nullable=False),
    sa.Column('payment_due_date', sa.String(), nullable=True),
    sa.Column('previous_balance_gtq', sa.Float(), nullable=True),
    sa.Column('purchases_gtq', sa.Float(), nullable=True),
    sa.Column('payments_gtq', sa.Float(), nullable=True),
    sa.Column('purchases_usd', sa.Float(), nullable=True),
    sa.Column('payments_usd', sa.Float(), nullable=True),
    sa.Column('current_balance_gtq', sa.Float(), nullable=True),
    sa.Column('previous_balance_usd', sa.Float(), nullable=True),
    sa.Column('current_balance_usd', sa.Float(), nullable=True),
    sa.Column('credit_limit_gtq', sa.Float(), nullable=True),
    sa.Column('available_credit_gtq', sa.Float(), nullable=True),
    sa.Column('minimum_payment_gtq', sa.Float(), nullable=True),
    sa.Column('annual_interest_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number_masked', 'cut_off_date', name='uq_statement')
    )
    op.create_index('idx_transactions_statement_id', 'statements', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('operation_date', sa.String(), nullable=False),
    sa.Column('consumption_date', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('credit_card_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index('idx_transactions_statement_id', table_name='statements')
    op.drop_table('statements')
    # ### end Alembic commands ###
